version: "3.7"

services:
  django:
    container_name: quering-django-prod
    user: $UID:$GID
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app:Z
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    command: >
      sh -c "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && python manage.py initdb && gunicorn app.wsgi:application --timeout 800 --bind 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=covid19th
      - DB_USER=covid19
      - DB_PASS=postgres2562
      - SECRET_KEY=3thwz0c7yn)+n10s22i@c!n0)l@&82n#$$q6qk*9@nz-0y-$$0s7
      - EMAIL_HOST=smtp.sendgrid.net
      - EMAIL_HOST_USER=ben@covid19
      - EMAIL_HOST_PASSWORD=benning43609
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=True
      - DEBUG=False
      - TYPE=prod
    depends_on:
      - db

  db:
    container_name: quering-db-covid-prod
    image: postgres:11-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=covid19th
      - POSTGRES_USER=covid19
      - POSTGRES_PASSWORD=postgres2562
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./docker_volumes/pg_data:/var/lib/postgresql/data

  frontend:
    container_name: quering-frontend-covid-prod
    build:
      context: ./front-end-covit-help-master
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  nginx-ssl:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'helpital.org, covid19th.org'
      SITES: 'helpital.org=nginx:80;*.covid19th.org=nginx:80'

  nginx:
    container_name: quering-nginx-covid-prod
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    depends_on:
      - frontend
      - django

volumes:
  media_volume:
  static_volume:
  ssl_data:

